USE [master]
GO

/****** Object:  Database [projectdb]    Script Date: 11-Apr-19 12:48:08 AM ******/
DROP DATABASE [projectdb]
GO

/****** Object:  Database [projectdb]    Script Date: 11-Apr-19 12:48:08 AM ******/
CREATE DATABASE [projectdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'projectdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\projectdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'projectdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\projectdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [projectdb] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [projectdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [projectdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [projectdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [projectdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [projectdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [projectdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [projectdb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [projectdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [projectdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [projectdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [projectdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [projectdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [projectdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [projectdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [projectdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [projectdb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [projectdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [projectdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [projectdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [projectdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [projectdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [projectdb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [projectdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [projectdb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [projectdb] SET  MULTI_USER 
GO

ALTER DATABASE [projectdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [projectdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [projectdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [projectdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [projectdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [projectdb] SET QUERY_STORE = OFF
GO

USE [projectdb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [projectdb] SET  READ_WRITE 
GO


